const List<String> statementInstituionsList = [
  'Fifth Third Bank',
  'Huntington Bank',
  'Navy Federal Credit Union',
  'Regions Bank',
  'U.S. Bank',
  'Wells Fargo',
  'Bank of America',
  'Citibank Online',
  'TD Bank',
  'Atlas',
  'First Platypus Bank',
  'First Platypus Bank - OAuth',
  'GuideStone Financial Resources',
  'Mass Finance Inc.',
  'Parker',
  'Percapita Group, Inc',
  'Platypus OAuth Bank',
  'Safra National Bank',
  'Seventh Bank of Northwestern Natick',
  'Slash',
  'Truist',
  'Upgrade',
];
